[module.hugoVersion]
extended = true

[[module.imports]]
path = "github.com/FortAwesome/Font-Awesome"

[[module.imports.mounts]]
source = "js-packages/@fortawesome"
target = "assets/js/font-awesome"

[params.hugopress.modules.font-awesome.hooks.body-end]
