title = "Hugo Font Awesome SVG JS Module"
theme = [
    "github.com/razonyang/hugo-mod-font-awesome-svg-js"
]

[[module.imports]]
path = "github.com/razonyang/hugopress"
[[module.imports]]
path = "github.com/razonyang/hugo-mod-font-awesome-svg-js/exampleSite/modules/foo"
[[module.imports]]
path = "github.com/razonyang/hugo-mod-font-awesome-svg-js/exampleSite/modules/bar"

[params.fontAwesome.icons.regular.file]
